node {
        
        properties([parameters([string(defaultValue: 'anzchallenge', name: 'S3_BUCKET_NAME', trim: true)])])

            stage('Destroy EKS'){
                echo 'Destroying Infrastructure for ANZ Challenge App!' 
                deleteDir()
                checkout([$class: 'GitSCM', branches:[[name: "master"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "https://github.com/DJEnterprise/anzchallengeiac.git"]]])
                sh """ 
                cd terraform/anzchallenge
                terraform init -backend-config=bucket=anzchallenge -backend-config=key=anzchallenge/app.tfstate -backend-config=region=ap-southeast-2
                terraform destroy \
                -var-file=\"nonprod.tfvars\" \
                -auto-approve
                """
                }
    
}
    