node {
    
    
        stage('Stage Build') {
            
                echo 'Building ANZ Challenge App!' 
            stage('Build Java'){
                deleteDir()
                checkout([$class: 'GitSCM', branches:[[name: "master"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "https://github.com/DJEnterprise/anzchallenge.git"]]])
                sh """ 
                ./gradlew build
                """
                }
            stage('Build Docker Image'){
                
            }
            }
}
    
