node {

        stage('Stage Build Infrastructure') {
            
         echo 'Building Infrastructure for ANZ Challenge App!' 
            stage('Build EKS'){
                deleteDir()
                checkout([$class: 'GitSCM', branches:[[name: "master"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "https://github.com/DJEnterprise/anzchallengeiac.git"]]])
                sh """ 
                cd terraform/anzchallenge
                terraform init
                terraform apply \
                -var-file=\"nonprod.tfvars\" \
                -autoapprove
                """
                }
        }
}
    
